include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/**.g.dart

  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning

linter:
  rules:

    # =========================
    # BOAS PRÁTICAS GERAIS
    # =========================
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    unnecessary_this: true

    # =========================
    # LEGIBILIDADE & PADRÃO
    # =========================
    always_declare_return_types: true
    type_annotate_public_apis: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: false

    # =========================
    # NULL SAFETY
    # =========================
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true

    # =========================
    # ARQUITETURA (MVVM)
    # =========================
    avoid_classes_with_only_static_members: true
    use_build_context_synchronously: true

    # =========================
    # ASYNC / AWAIT
    # =========================
    unawaited_futures: true
    avoid_void_async: true

    # =========================
    # COLEÇÕES & MODELOS
    # =========================
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_collection_literals: true

    # =========================
    # BOAS PRÁTICAS FLUTTER
    # =========================
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # =========================
    # FLEXIBILIDADE (DESLIGADAS DE PROPÓSITO)
    # =========================
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
