// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUteI5uVd-ZBmcdOhcP6aCjzQmX2st7OE',
    appId: '1:228969276268:web:29c2aa99717ed78c61c949',
    messagingSenderId: '228969276268',
    projectId: 'veronicalenstg',
    authDomain: 'veronicalenstg.firebaseapp.com',
    storageBucket: 'veronicalenstg.firebasestorage.app',
    measurementId: 'G-MN22PCRX8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTa3_92LP0QEDI_ed_MGp7AM-BB6zXfs',
    appId: '1:228969276268:android:cfb0238fcdbc05b461c949',
    messagingSenderId: '228969276268',
    projectId: 'veronicalenstg',
    storageBucket: 'veronicalenstg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6AA-BmSYH3doSklX8yLMxkwkdNW9JA3Y',
    appId: '1:228969276268:ios:19f0776c671b181b61c949',
    messagingSenderId: '228969276268',
    projectId: 'veronicalenstg',
    storageBucket: 'veronicalenstg.firebasestorage.app',
    iosBundleId: 'com.example.veronicalensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6AA-BmSYH3doSklX8yLMxkwkdNW9JA3Y',
    appId: '1:228969276268:ios:19f0776c671b181b61c949',
    messagingSenderId: '228969276268',
    projectId: 'veronicalenstg',
    storageBucket: 'veronicalenstg.firebasestorage.app',
    iosBundleId: 'com.example.veronicalensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUteI5uVd-ZBmcdOhcP6aCjzQmX2st7OE',
    appId: '1:228969276268:web:cf13632825c4435961c949',
    messagingSenderId: '228969276268',
    projectId: 'veronicalenstg',
    authDomain: 'veronicalenstg.firebaseapp.com',
    storageBucket: 'veronicalenstg.firebasestorage.app',
    measurementId: 'G-NRYKEYTCT4',
  );
}
